/** Frontend subscription plan definitions — mirrors Backend/src/modules/subscription/subscription.config.js */

export const SUBSCRIPTION_PLANS = [
  {
    id: "plan_7d",
    name: "7 Days",
    label: "Weekly",
    days: 7,
    realPrice: 99,
    offerPrice: 79,
    saving: 20,
    perMonth: "₹11.3/week",
    popular: false,
    badge: null,
    color: "#6366f1",
  },
  {
    id: "plan_1m",
    name: "1 Month",
    label: "Monthly",
    days: 30,
    realPrice: 349,
    offerPrice: 299,
    saving: 50,
    perMonth: "₹299/mo",
    popular: false,
    badge: null,
    color: "#06b6d4",
  },
  {
    id: "plan_3m",
    name: "3 Months",
    label: "Quarterly",
    days: 90,
    realPrice: 899,
    offerPrice: 799,
    saving: 100,
    perMonth: "₹266/mo",
    popular: true,
    badge: "Most Popular",
    color: "#8b5cf6",
  },
  {
    id: "plan_6m",
    name: "6 Months",
    label: "Half Yearly",
    days: 180,
    realPrice: 1599,
    offerPrice: 1299,
    saving: 300,
    perMonth: "₹216/mo",
    popular: false,
    badge: "Best Value",
    color: "#10b981",
  },
  {
    id: "plan_12m",
    name: "12 Months",
    label: "Yearly",
    days: 365,
    realPrice: 2999,
    offerPrice: 2199,
    saving: 800,
    perMonth: "₹183/mo",
    popular: false,
    badge: "🎉 Max Savings",
    color: "#f59e0b",
  },
];
